/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

/**
 *
 * @author Jay
 * 
 * Manage all invoices generated by user purchases
 * 
 */
public class InvoiceManager {
    
}
