/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

import data.Item;
import java.io.FileNotFoundException;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;
import java.util.ArrayList;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.Util;


/**
 *
 * @author Jay
 * 
 * Manage all invoices generated by user purchases
 * 
 */
public class InvoiceManager {
    ArrayList<Invoice> all_invoices;
    
    // load invoices
    
    // save invoices
    
    // get/setters?
    
    // some other system helpers
}
